{{- if .Values.rhtpa.zeroTrust.oidc.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.rhtpa.zeroTrust.oidc.clients.cli.secretName | default "rhtpa-oidc-cli-secret" }}
  namespace: {{ .Values.rhtpa.namespace }}
  labels:
    {{- include "rhtpa-operator.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # Create before RHTPA CR
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: {{ .Values.rhtpa.zeroTrust.oidc.clients.cli.secretName | default "rhtpa-oidc-cli-secret" }}
    creationPolicy: Owner
  data:
  - secretKey: client-secret
    remoteRef:
      key: {{ .Values.rhtpa.zeroTrust.oidc.clients.cli.secretVaultPath }}
      property: client-secret
{{- end }}

