{{- if .Values.keycloak.defaultConfig }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: rhtpa-oidc-cli-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: rhtpa-oidc-cli-secret
    template:
      type: Opaque
      data:
        client-secret: "{{ `{{ .client_secret }}` }}"
  data:
  - secretKey: client_secret
    remoteRef:
      key: {{ .Values.keycloak.oidcSecrets.rhtpaCli.vaultPath }}
      property: client-secret
{{- end }}

