{{- if eq .Values.rhtas.oidc.enabled true }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: {{ .Values.rhtas.oidc.clientSecretName }}
  namespace: {{ .Release.Namespace | default .Values.global.namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: {{ .Values.rhtas.oidc.clientSecretName }}
    template:
      type: Opaque
      data:
        client-secret: "{{ `{{ .password }}` }}"
  data:
  - secretKey: password
    remoteRef:
      key: {{ .Values.rhtas.oidc.clientSecretVaultPath }}
      property: {{ .Values.rhtas.oidc.clientSecretVaultKey }}
{{- end }}