{{- if eq .Values.quay.enabled true }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.quay.jobs.caExtractor.serviceAccountName }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.quay.jobs.caExtractor.serviceAccountName }}-role
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "create", "update", "patch"]
  - apiGroups: ["config.openshift.io"]
    resources: ["images"]
    verbs: ["get", "patch", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.quay.jobs.caExtractor.serviceAccountName }}-role-binding
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
subjects:
  - kind: ServiceAccount
    name: {{ .Values.quay.jobs.caExtractor.serviceAccountName }}
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.quay.jobs.caExtractor.serviceAccountName }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}