{{- if .Values.app.images.main.registry.auth }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: {{ .Values.app.images.main.registry.secretName }}
  namespace: {{ .Release.Namespace | default .Values.global.namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.global.secretStore.name }}
    kind: {{ .Values.global.secretStore.kind }}
  target:
    name: {{ .Values.app.images.main.registry.secretName }}
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "{{ required "app.images.main.registry.domain is required when registry.auth is enabled" .Values.app.images.main.registry.domain }}": {
                "auth": "{{ `{{ printf "%s:%s" "` }}{{ .Values.app.images.main.registry.user }}{{ `" .password | b64enc }}` }}"
              }
            }
          }
  data:
  - secretKey: password
    remoteRef:
      {{- if .Values.app.images.main.registry.builtinQuay.enabled }}
      key: {{ .Values.app.images.main.registry.builtinQuay.vaultPath }}
      property: {{ .Values.app.images.main.registry.builtinQuay.passwordVaultKey }}
      {{- else if .Values.app.images.main.registry.externalRegistry.enabled }}
      key: {{ .Values.app.images.main.registry.externalRegistry.vaultPath }}
      property: {{ .Values.app.images.main.registry.externalRegistry.passwordVaultKey }}
      {{- end }}
{{- end }}